# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  linux:
    strategy:
      matrix:
        container:
        - 'centos:7'
    timeout-minutes: 300
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: Build
      uses: docker/build-push-action@v1
